{
    "name": "Exam_Application",
    "version": "15.0.1.0.0",
    "summary": "this is an examination application",
    "description": "this is examination application where it has details of students,faculties,supervisors,subjects.",
    "author": "bizzappdev",
    "website": "https://www.bizzappdev.com",
    "data": [
        "security/ir.model.access.csv",
        "views/exam_views.xml",
        "views/student_views.xml",
        "views/faculty_views.xml",
        "views/supervisor_views.xml",
        "views/subject_views.xml",
        "views/exam_menus_views.xml",
    ],
    "depends": ["base"],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
